### ISSUE TITLE
Varnish doesn't work w/ NextJS

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-mui#142]
I tried to create a NextJS template from the latest version of Next (13). Varnish doesn't work.

I'll have a template shortly, which can be used to reproduce the problem. For now I'll add basic steps:

1. `npx create-next-app@latest`
2. `yarn add @allenai/varnish2 @emotion/react @emotion/styled @mui/icons-material @mui/lab @mui/material styled-compoennts`
3. Edit `app/src/app/layout.tsx` to look like so:

    ```tsx
    import './globals.css'
    import type { Metadata } from 'next'
    import { VarnishApp } from '@allenai/varnish2/components';

    export const metadata: Metadata = {
        title: 'Skiff NextJS Template',
        description: 'A Skiff Template that uses NextJS',
    }

    export default function RootLayout({
      children,
    }: {
      children: React.ReactNode
    }) {
      return (
        <html lang="en">
            <head>
              <link
                rel="stylesheet"
                href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap"
              />
            </head>
            <body>
                <VarnishApp>
                    {children}
                </VarnishApp>
            </body>
        </html>
      )
    }
    ```

4. Run `yarn dev`
5. Navigate to http://localhost:3000

Things wont' work. Instead you'll see this error:

```
- error createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component
    at eval (webpack-internal:///(rsc)/./node_modules/styled-components/dist/styled-components.cjs.js:505:44)
    at (rsc)/./node_modules/styled-components/dist/styled-components.cjs.js (/Users/sams/hack/skiff-template-nextjs/app/.next/server/app/page.js:7450:1)
    at __webpack_require__ (/Users/sams/hack/skiff-template-nextjs/app/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@allenai/varnish2/node/components/Content.js:11:49)
    at (rsc)/./node_modules/@allenai/varnish2/node/components/Content.js (/Users/sams/hack/skiff-template-nextjs/app/.next/server/app/page.js:6243:1)
    at __webpack_require__ (/Users/sams/hack/skiff-template-nextjs/app/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@allenai/varnish2/node/components/index.js:5:16)
    at (rsc)/./node_modules/@allenai/varnish2/node/components/index.js (/Users/sams/hack/skiff-template-nextjs/app/.next/server/app/page.js:6364:1)
    at __webpack_require__ (/Users/sams/hack/skiff-template-nextjs/app/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./src/app/layout.tsx:9:86) {
  name: 'TypeError',
  digest: undefined
}
```

**Comment by codeviking** [comment]
I'm going to omit Varnish in the template for now. Once this is fixed it'd be nice if someone added it, as I think that's preferable.

**Comment by codeviking** [comment]
Here's the template:
https://github.com/allenai/skiff-template-nextjs
